name: Process Data Repository
on:
  push:
    branches:
      - 'main'
jobs:
  update_public_repo:
    if: github.repository == 'uva-bi-sdad/sdc.education_dev'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master    
      - name: List current working directory
        run: |
          ls -la  
      - name: Pull latest git repo
        run : |
          git pull
      - name: Remove all files that do not have a distribution in its path, ignoring all files in root
        run: |
          find ${{ github.workspace }} -mindepth 2 -type f ! -wholename "**/distribution/*" -delete
      - name: Remove github things # Required so that you can push to another directory
        run: |
          rm -rf .git
      - name: Print working directory
        run: |
          pwd
      - name: List current working directory
        run: |
          tree .
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SDC_SECRET }}
        with:
          source-directory: .
          destination-github-username: 'uva-bi-sdad'
          destination-repository-name: 'sdc.education'
          target-branch: main
      - run: echo "🍏 This job's status is ${{ job.status }}."
